name: FitAdvisor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.12.0
  google_mlkit_commons: ^0.7.1
  kinestex_sdk_flutter: ^1.0.5
  google_ml_kit: ^0.18.0
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.19.4
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
