// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jiRMoX0IeWjQGSUfsnK3kCzu-mccvIM',
    appId: '1:771443256393:web:e63bf48c14dc0ef9bee398',
    messagingSenderId: '771443256393',
    projectId: 'fitadvisor-flutter',
    authDomain: 'fitadvisor-flutter.firebaseapp.com',
    storageBucket: 'fitadvisor-flutter.appspot.com',
    measurementId: 'G-36793W9NJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJXf2io6FRTw0zfvLSs9rpICy6c7yvWQ',
    appId: '1:771443256393:android:6cac6a68fd1c7120bee398',
    messagingSenderId: '771443256393',
    projectId: 'fitadvisor-flutter',
    storageBucket: 'fitadvisor-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGi7hA84a4KFGHn6ScETaxnYtOhuq2C2Y',
    appId: '1:771443256393:ios:7a30303591ed8e43bee398',
    messagingSenderId: '771443256393',
    projectId: 'fitadvisor-flutter',
    storageBucket: 'fitadvisor-flutter.appspot.com',
    iosBundleId: 'com.example.fitadvisor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGi7hA84a4KFGHn6ScETaxnYtOhuq2C2Y',
    appId: '1:771443256393:ios:7a30303591ed8e43bee398',
    messagingSenderId: '771443256393',
    projectId: 'fitadvisor-flutter',
    storageBucket: 'fitadvisor-flutter.appspot.com',
    iosBundleId: 'com.example.fitadvisor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4jiRMoX0IeWjQGSUfsnK3kCzu-mccvIM',
    appId: '1:771443256393:web:f369d7469524dfc8bee398',
    messagingSenderId: '771443256393',
    projectId: 'fitadvisor-flutter',
    authDomain: 'fitadvisor-flutter.firebaseapp.com',
    storageBucket: 'fitadvisor-flutter.appspot.com',
    measurementId: 'G-V5ZCNKDMY3',
  );

}